### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by FunniMonke** [MorvanZhou/mmaze#1]
May I ask why the printed version of the maze is so much different from the plotted version of the maze? I am trying to make an ASCII-type game so it would be quite helpful if the printed version of the maze bared resemblance to the plotted version of it.

**Comment by MorvanZhou** [comment]
Could you please show some example code so I can have a look of this problem?

**Comment by MorvanZhou** [comment]
It may due to the print symbol I used. I have changed to "||" for walls. So it would print like this.

```python
"""
||||||||||||||
||      ||  ||
||||||  ||  ||
||  ||      ||
||  ||||||  ||
||          ||
||||||||||||||
"""
```
